version: "3.7"

services:
  dwh_db:
    image: postgres:12.5-alpine
    restart: unless-stopped
    container_name: dwh_db
    tty: true
    environment:
      POSTGRES_DB: dwh_db
      POSTGRES_USER: dwh_db
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - dwh_db_data:/var/lib/postgresql/data/
    networks:
      - dwh_network
networks:
  dwh_network:
    driver: bridge

volumes:
  dwh_db_data: